# Generated by Django 4.2.3 on 2023-09-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='avatar',
            field=models.FileField(blank=True, max_length=300, upload_to='Uploads', verbose_name='User Avatar'),
        ),
    ]
