# Generated by Django 4.2.3 on 2023-09-17 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_alter_siteuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='messageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageContent', models.TextField(verbose_name='Mesaj İçeriği')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Toplam Görüntülenme')),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='Oluşturma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_author', to=settings.AUTH_USER_MODEL, verbose_name='Mesaj Yazarı')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_avatar', to=settings.AUTH_USER_MODEL, verbose_name='Mesaj yazarı Avatar')),
            ],
        ),
    ]
