# Generated by Django 4.2.3 on 2023-09-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_messagedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagedetail',
            name='avatar',
        ),
    ]
