# Generated by Django 4.2.3 on 2023-09-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='about',
            field=models.TextField(default='Hakkimda', verbose_name='Hakkinda'),
        ),
    ]
