# Generated by Django 4.2.3 on 2023-09-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0007_siteuser_github_siteuser_instagram_siteuser_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='about',
            field=models.CharField(default='Hakkimda', max_length=100, verbose_name='Hakkimda'),
        ),
    ]
