# Generated by Django 4.2.3 on 2023-09-20 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0008_alter_siteuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedetail',
            name='likes',
            field=models.ManyToManyField(related_name='message_post', to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
    ]
