# Generated by Django 4.2.3 on 2023-09-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0010_messagedetail_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedetail',
            name='postViews',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='View'),
        ),
    ]
