# Generated by Django 4.2.3 on 2023-09-21 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0011_messagedetail_postviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='followers'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='following',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='following'),
        ),
    ]
