# Generated by Django 4.2.3 on 2023-09-21 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0012_siteuser_followers_siteuser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='followers'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='following',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='following'),
        ),
    ]
