# Generated by Django 4.2.3 on 2023-09-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0013_alter_siteuser_followers_alter_siteuser_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='github',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='twitter',
        ),
    ]
