# Generated by Django 4.2.3 on 2023-09-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0015_bannedusers_siteuser_banrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannedusers',
            options={'verbose_name': 'Banned Users', 'verbose_name_plural': 'Banned Users'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comments', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='messagedetail',
            options={'verbose_name': 'Posts', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='siteuser',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
    ]
