# Generated by Django 4.2.3 on 2023-09-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0016_alter_bannedusers_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='following',
        ),
    ]
