# Generated by Django 4.2.3 on 2023-10-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0017_remove_siteuser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='avatar',
            field=models.ImageField(blank=True, max_length=300, upload_to='Uploads', verbose_name='User Avatar'),
        ),
    ]
